global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'triton-inference-server'
    static_configs:
      - targets: ['triton-inference-server:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['ai-redis:6379']

  - job_name: 'nginx'
    static_configs:
      - targets: ['ai-nginx:80']
