# Certificate for external domains
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-infrastructure-tls
  namespace: ai-infrastructure
spec:
  secretName: ai-infrastructure-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ai-api.yourdomain.com
  - ai-stt.yourdomain.com
  - ai-tts.yourdomain.com
  - ai-vllm.yourdomain.com
---
# Certificate for single domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-infrastructure-single-tls
  namespace: ai-infrastructure
spec:
  secretName: ai-infrastructure-single-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - ai.yourdomain.com
---
# ClusterIssuer for Let's Encrypt (if not already exists)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@yourdomain.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
# ClusterIssuer for Let's Encrypt staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: your-email@yourdomain.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
