apiVersion: v1
kind: Service
metadata:
  name: ai-routing-api
  namespace: ai-infrastructure
  labels:
    app: ai-routing-api
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ai-routing-api
---
apiVersion: v1
kind: Service
metadata:
  name: ai-vllm-service
  namespace: ai-infrastructure
  labels:
    app: ai-vllm-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: ai-vllm-service
---
apiVersion: v1
kind: Service
metadata:
  name: ai-stt-service
  namespace: ai-infrastructure
  labels:
    app: ai-stt-service
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: ai-stt-service
---
apiVersion: v1
kind: Service
metadata:
  name: ai-tts-service
  namespace: ai-infrastructure
  labels:
    app: ai-tts-service
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app: ai-tts-service
---
apiVersion: v1
kind: Service
metadata:
  name: ai-redis
  namespace: ai-infrastructure
  labels:
    app: ai-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: ai-redis
