apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-kong-ingress-https
  namespace: ai-infrastructure
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "http,https"
    konghq.com/plugins: "ai-cors,ai-rate-limit,ai-request-transformer"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - api.askcollections.com
    secretName: api-askcollections-com-tls
  rules:
  - host: api.askcollections.com
    http:
      paths:
      # Main AI Routing API
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ai-routing-api
            port:
              number: 8001
      # Speech-to-Text Service
      - path: /stt
        pathType: Prefix
        backend:
          service:
            name: ai-stt-service
            port:
              number: 8002
      # Text-to-Speech Service
      - path: /tts
        pathType: Prefix
        backend:
          service:
            name: ai-tts-service
            port:
              number: 8003
      # Direct vLLM Service
      - path: /vllm
        pathType: Prefix
        backend:
          service:
            name: ai-vllm-service
            port:
              number: 8000
      # Health check endpoint
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: ai-routing-api
            port:
              number: 8001
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-cors
  namespace: ai-infrastructure
config:
  origins:
  - "*"
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  - PATCH
  headers:
  - Accept
  - Accept-Version
  - Content-Length
  - Content-MD5
  - Content-Type
  - Date
  - X-Auth-Token
  - Authorization
  - X-Requested-With
  - X-Session-ID
  - X-User-ID
  exposed_headers:
  - X-Auth-Token
  credentials: true
  max_age: 3600
  preflight_continue: false
plugin: cors
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-rate-limit
  namespace: ai-infrastructure
config:
  minute: 1000
  hour: 10000
  day: 100000
  policy: local
plugin: rate-limiting
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-request-transformer
  namespace: ai-infrastructure
config:
  add:
    headers:
    - "X-Forwarded-Proto:https"
    - "X-Real-IP:$(remote_addr)"
  remove:
    headers:
    - "X-Forwarded-For"
plugin: request-transformer
